# docker-compose.override.yaml ( dev )
# version: '3.8'

services:
  database:
    image: 'mariadb:11.0'
    container_name: database_clickandwear_dev
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ClickAndWear
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 3
      start_period: 30s
    volumes:
          - database_data_clickandwear:/var/lib/mysql
    ports:
        - '3308:3306'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_clickandwear_dev
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    ports:
        - 8089:80

  mailcatcher:
    image: dockage/mailcatcher:0.9.0
    container_name: mailcatcher_clickandwear_dev
    restart: on-failure
    ports:
        - '1027:1025'
        - '1089:1080'

volumes:
  database_data_clickandwear:
